generate-load:
  image: registry.gitlab.com/checkelmann/cicd-tools:latest
  stage: test
  variables:
    GIT_STRATEGY: fetch
  script: |
    # Get Endpoint for Load test
    echo $(date --utc +%FT%TZ) > ${CI_ENVIRONMENT_NAME}_teststart.txt
    /opt/apache-jmeter-5.2.1/bin/jmeter -n -t ./jmeter/simplenodeservice_load.jmx \
      -l ${CI_ENVIRONMENT_SLUG}_perf.tlf \
      -JSERVER_URL="simplenodeservice.simplenode-gitlab-staging" \
      -JSERVER_PORT=80 \
      -JVUCount=2 \
      -JLoopCount=150 \
      -JThinkTime=100 \
      -JDT_LTN="PerfCheck_${CI_COMMIT_SHA}"
    
    echo $(date --utc +%FT%TZ) > ${CI_ENVIRONMENT_NAME}_testend.txt
    #cat ${CI_ENVIRONMENT_SLUG}_perf.tlf
  artifacts:
    paths:
      - ${CI_ENVIRONMENT_SLUG}_perf.tlf
      - ${CI_ENVIRONMENT_NAME}_teststart.txt
      - ${CI_ENVIRONMENT_NAME}_testend.txt
    expire_in: 1 day