---
- include_role:
    name: microk8s

# - include_role:
#     name: dt-activegate

# - include_role:
#     name: dt-oneagent

# - include_role:
#     name: monaco

# - include_role:
#     name: monaco
#     tasks_from: dt-cleanup

# - include_role:
#     name: keptn
#   when: cloud_automation_flavor is defined and cloud_automation_flavor == "KEPTN"

# - include_role:
#     name: cloudautomation
#   when: cloud_automation_flavor is defined and cloud_automation_flavor == "CLOUD_AUTOMATION"

# - include_role:
#     name: gitea

# - include_role:
#     name: gitea
#     tasks_from: source-secret
#   when: gitea_access_token is not defined or gitea_username is not defined or gitea_password is not defined

# - include_role:
#     name: gitea
#     tasks_from: create-organization
#   vars:
#     gitea_org: "{{ demo_default_org }}"

# - include_role:
#     name: gitea
#     tasks_from: create-repository
#   vars:
#     gitea_org: "{{ demo_default_org }}"
#     gitea_repo: "{{ demo_default_repo_name }}"

# - include_role:
#     name: repository
#   vars:
#     repo_src: "{{ item.repo_src }}"
#     git_org: "{{ item.git_org }}"
#     git_repo: "{{ item.repo_target }}"
#     git_username: "{{ gitea_username }}"
#     git_password: "{{ gitea_password }}"
#     git_domain: "{{ gitea_domain }}"
#     git_remote: "gitea"
#   loop:
#   - { repo_target: "{{ demo_default_repo_name }}", repo_src: "./roles/use-case/files/ace", git_org: "{{ demo_default_org }}" }
#   when: new_repo_created is defined and new_repo_created == true

- include_role:
    name: jenkins
  vars:
    jenkins_additional_templates:
    - name: "demo-default"
      src: "./roles/use-case/templates/jenkins-demo-default.yml.j2"

# - include_role:
#     name: dashboard
