# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- include_role:
    name: dt-access-token
  vars:
    access_token_var_name: "{{ dt_operator_dt_access_token_name }}"
    access_token_scope: ["DataExport", "InstallerDownload", "activeGateTokenManagement.create", "entities.read", "settings.read", "settings.write"]

- include_role:
    name: dt-access-token
  vars:
    access_token_var_name: "{{ dt_operator_dt_data_ingest_token_name }}"
    access_token_scope: ["metrics.ingest"] 

- name: Create Dynatrace namespace
  kubernetes.core.k8s:
    name: "{{ dt_operator_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- file:
    path: "{{ role_path }}/files"
    state: directory

- block:
  - name: Download dynatrace-operator manifest
    ansible.builtin.get_url:
      url: "https://github.com/Dynatrace/dynatrace-operator/releases/download/{{ dt_operator_release }}/kubernetes.yaml"
      dest: "{{ role_path }}/files/dt_operator.yaml"
      mode: '0664'
  - name: Apply dynatrace-operator manifest
    kubernetes.core.k8s:
      state: present
      src: "{{ role_path }}/files/dt_operator.yaml"
    register: dt_operator
    retries: 20
    delay: 5
    until: dt_operator is not failed
  when: operator_mode != "applicationMonitoring"

- name: Add stable chart repo
  kubernetes.core.helm:
    name: dynatrace-operator
    chart_ref: "oci://public.ecr.aws/dynatrace/dynatrace-operator"
    # set_values:
    #   - value: imageRef.repository=gcr.io/dynatrace-marketplace-prod/dynatrace-operator
    #     value_type: string
    release_namespace: dynatrace
    create_namespace: true
    atomic: true
    chart_version: "{{dt_operator_release}}"
  when: operator_mode == "applicationMonitoring"

- block:
  - name: Download CSI manifest
    ansible.builtin.get_url:
      url: "https://github.com/Dynatrace/dynatrace-operator/releases/download/{{ dt_operator_release }}/kubernetes-csi.yaml"
      dest: "{{ role_path }}/files/dt_operator-csi.yaml"
      mode: '0664'
  - name: Apply CSI manifest
    kubernetes.core.k8s:
      state: present
      src: "{{ role_path }}/files/dt_operator-csi.yaml"
    register: dt_operator_csi
    retries: 20
    delay: 5
    until: dt_operator_csi is not failed
  when: operator_mode != "applicationMonitoring"

- block:
  - name: Template Dynakube manifest
    ansible.builtin.template:
      src: "{{ operator_mode }}.yaml.j2"
      dest: "{{ role_path }}/files/{{ operator_mode }}.yaml"
      owner: "{{ ace_box_user }}"
      group: "{{ ace_box_user }}"
      mode: "0644"
  - name: Apply Dynakube manifest
    kubernetes.core.k8s:
      state: present
      src: "{{ role_path }}/files/{{ operator_mode }}.yaml"
    register: dynakube
    retries: 20
    delay: 20
    until: dynakube is not failed

- block:
  - name: Wait for at least one Dynatrace OneAgent pod to be created
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: dynatrace
      label_selectors:
        - "app.kubernetes.io/name=oneagent"
    register: dt_oneagent_pods_creation
    until: dt_oneagent_pods_creation.resources | length > 0
    retries: 20
    delay: 20
  - name: Wait for at least one Dynatrace ActiveGate pod to be created
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: dynatrace
      label_selectors:
        - "app.kubernetes.io/name=activegate"
    register: dt_activegate_pods_creation
    until: dt_activegate_pods_creation.resources | length > 0
    retries: 20
    delay: 20
  - name: Ensure all Dynatrace OneAgent pods are in Running state and ready
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: dynatrace
      label_selectors:
        - "app.kubernetes.io/name=oneagent"
    register: dt_oneagent_pods
    until: >
      dt_oneagent_pods.resources | selectattr('status.phase', 'equalto', 'Running') | map(attribute='status.containerStatuses') | selectattr('0.ready', 'equalto', true) | length == dt_oneagent_pods.resources | length
    retries: 20
    delay: 20
  - name: Ensure all Dynatrace ActiveGate pods are in Running state and ready
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: dynatrace
      label_selectors:
        - "app.kubernetes.io/name=activegate"
    register: dt_activegate_pods
    until: >
      dt_activegate_pods.resources | selectattr('status.phase', 'equalto', 'Running') | map(attribute='status.containerStatuses') | selectattr('0.ready', 'equalto', true) | length == dt_activegate_pods.resources | length
    retries: 20
    delay: 20
  when: operator_mode == "classicFullStack"

- include_role:
    name: fluentbit
  when: log_monitoring == "fluentbit"

- include_role:
    name: edge-connect
  when: edge_connect == true