---
# 
# my-use-case is the only required role.
# However, in addition to tasks in my-use-case, 
# additional roles can be included.
# Such roles can either be provided as part the
# external repo or included from a curated list
# of ACE-Box default roles.
# 
- debug:
    msg: "Hello from {{ my_ext_use_case_name }}!"

# 
# microk8s and dt-oneagent are curated roles provided by 
# the ACE-Box.
# Curated roles can be sourced from within your use case.
# 
- include_role:
    name: "microk8s"

- include_role:
    name: "dt-oneagent"

# 
# All other roles provided in an external use case are 
# synched with the ACE-Box Ansible directory and can
# therefore be sourced just like curated roles.
# 
- include_role:
    name: "another-role"
